### PR TITLE
soft_ccECP_4p_upf

### PR DESCRIPTION
**Pull request by gmwang18**
I added soft version of ccECPs for Mn, Fe, Co, Ni atoms.
Ga-Kr upf files are added as well.

### CODE REVIEW

**Comment by prckent** [comment]
- Can you say a little more about the softening and the cutoffs that are now needed, what testing was done?
- I think it should be "deprecated" not "depreciated" We don't have a history for many potentials yet, but we might label old potentials as deprecated_v1, _v2 etc. as we gain more.

**Comment by gmwang18** [comment]
> * Can you say a little more about the softening and the cutoffs that are now needed, what testing was done?
> * I think it should be "deprecated" not "depreciated" We don't have a history for many potentials yet, but we might label old potentials as deprecated_v1, _v2 etc. as we gain more.

I will give a new PR for these, separating the PR of soft-version ccECPs and Ga-Kr.

1. These softed ccECPs are newly generated. They are different from the previous ccECP parameters. The KE cutoffs are 600-700 Ry(according to opium), which is about half or one-third of original ccECPs. They are suitable for plane-wave calculations and not published yet. We plan to include them in later papers for spin-orbit ccECPs. Will you think it's proper to add them here to use before publication?
2. Yes. That's "deprecated". I wanted to label the previous ccECP upf as "deprecated" and let people use the soft-version ccECPs for plane-wave purposes.

**Comment by prckent** [comment]
Thanks for the explanation. Much more affordable.

Can you push the renamed versions? (git mv, add, commit, push)

**Comment by gmwang18** [comment]
> Thanks for the explanation. Much more affordable.
> 
> Can you push the renamed versions? (git mv, add, commit, push)

Yep. I will push it later today. Thank you.

**Pull request closed without merging**
