### PR TITLE
Gaussian format

### PR DESCRIPTION
**Pull request by addman2**
I don't know why but Gaussian format is missing in the repository. It would be usefull for me (and some others) to have also this oe included.

Add Gaussian format for ECPs that match '[A-z]{1,2}\.ccECP.gamess' regex and basis sets that match '[A-z]{1,2}\.(aug-)?cc-p[A-Z1-9]+\.gamess'.

### CODE REVIEW

**Comment by prckent** [comment]
Thanks for these. It is a valid point. How did you prepare these? To keep them maintained and consistent in future we could use a tool+script to make these consistent with the molpro ones.

**Comment by addman2** [comment]
I can add the generating scripts to the repository as well if you want. Just tell where is an appropriate location.

**Comment by prckent** [comment]
Great to hear you have scripts and can contribute them. I suggest in a directory `recipe_scripts` at the top level to keep distinct from the website files and from the actual recipes.

**Comment by addman2** [comment]
There are two scripts. One is a command line utility I wrote a long time ago converting GAMESS format to Gaussian one and the second is walker through the recipes searching for Gamess formats.

**Comment by prckent** [comment]
Apologies for not already merging this. Will get this merged next week assuming  we  can run the scripts successfully.

**Comment by addman2** [comment]
np, tell me if there are some problems.

**Comment by prckent** [comment]
Was able to run your scripts for all the recently added ECPs and basis sets. I have not any with Gaussian, but the few I checked looked OK by eye.

Thanks again for these scripts and the conversions to Gaussian formats.

**Pull request merged**
